### ISSUE TITLE
Stop eating my whitespace

### ISSUE THREAD

**Issue by Alb0t** [poblahblahblah/burn-after-clicking#11]
If entering a yaml file, like a secret for kubernetes, the yaml becomes malformed on reading it back. Looks like it eats whitespaces.

Input:
```
hello:
    world
```

Output:
```
hello: 
world
```

**Comment by poblahblahblah** [comment]
addressed in https://github.com/poblahblahblah/burn-after-clicking/commit/a53f1fa548c7adaf1c8dc65100cf13406bd5f9a1
